# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    tags: 'v*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install XOrg Dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libx11-dev libx11-xcb-dev xserver-xorg-dev xorg-dev libxft-dev libxext-dev \
          libxrandr-dev libxi-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libpng-dev

    # Install latest CMake and Ninja.
    - uses: lukka/get-cmake@latest
      with:
        cmake-version: 'latest'
        cmake-generator: Ninja
        cmake-generator-args: '-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}'
    
    - name: Install vcpkg dependencies
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true
        vcpkgDirectory: ${{github.workspace}}/vcpkg
        VCPKG_DEFAULT_TRIPLET: x64-linux
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Get version from tag
      id: get_version
      run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Executable
      uses: softprops/action-gh-release@v1
      with:
        files: build/gtk_env_test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    
